### ISSUE TITLE
zcash params shared between 1p and 3p

### ISSUE THREAD

**Issue by Alrighttt** [smk762/notary_docker_3p#3]
Out of an abundance of caution, I recommend we change how the zcash params are made available to the 3p containers. We should make a duplicate directory `.3p_zcash-params` possibly or as smk recommends via DM, make the directory read-only

**Comment by Alrighttt** [comment]
`chmod 444 .zcash-params/`

Seems sufficient to prevent containers writing to this directory while maintaining access to the params files.

**Comment by smk762** [comment]
set to read only in https://github.com/smk762/notary_docker_3p/commit/0451853a00e7d6de95320aa7e98bf18457c20f49
