### ISSUE TITLE
configure.py writes unneeded spentindex and addressindex params in conf

### ISSUE THREAD

**Issue by dimxy** [smk762/notary_docker_3p#30]
When I installed notary_docker_3p repo on my dev main node I noticed unneeded spentindex=1 and addressindex=1 params both in my main and 3p nodes' komodo.conf (resulting in nodes reindexing).
Apparently configure.py adds those params in all generated chain conf files.
Adding those params causes spending extra hdd space and cpu timing. Only few chains like marmara actually need those params.

**Comment by smk762** [comment]
removed - https://github.com/smk762/notary_docker_3p/blob/main/configure.py#L249-L251
